# Generated by Django 5.0.2 on 2024-07-27 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="pbreport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_time", models.TextField()),
                ("channel", models.CharField(max_length=20)),
                ("security", models.CharField(max_length=10)),
                ("purpose", models.TextField(max_length=50)),
                ("content", models.TextField(max_length=500)),
                ("future_task", models.TextField()),
            ],
        ),
    ]
